package com.team11.foodorder.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Stores a one-time delivery verification code linked to a specific order.
 * Generated by admin, verified by the customer before delivery begins.
 */
@Entity
@Table(name = "delivery_otp")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DeliveryOtp {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The order this OTP belongs to. One order → one active OTP. */
    @Column(nullable = false, unique = true)
    private Long orderId;

    /** 6-digit numeric code. */
    @Column(nullable = false, length = 6)
    private String otpCode;

    /** When this OTP was generated. */
    @Column(nullable = false)
    private LocalDateTime generatedAt;

    /** OTP expires after this time (10 minutes from generation). */
    @Column(nullable = false)
    private LocalDateTime expiresAt;

    /** Whether this OTP has already been used (consumed on first success). */
    @Column(nullable = false)
    private boolean used;

    /** Convenience: is this OTP still valid (not used and not expired)? */
    @Transient
    public boolean isValid() {
        return !used && LocalDateTime.now().isBefore(expiresAt);
    }
}